### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by ChickenBone**
Add DPS as a school district that can use SchoologyPlus

### CODE REVIEW

**Comment by glen3b** [comment]
Thanks for the PR! Related: #82.

I think our general inclination has been to avoid special-casing other districts, with the hopes that we will add general support for any Schoology domain as per #82. For that reason I'd lean against accepting this PR, but I'm leaving it open for discussion. Concerns include that I don't know if we have a concrete schedule/feature-arc for general domain support.

CC @aopell

**Comment by ChickenBone** [comment]
For sure! I understand completely I can go through and see if I can find/verify that more than one school district can be added, I loaded the unpacked extension with this change on my local machine and it seems to be working perfectly (I have yet to find any issues) but I'll look more into adding general schoology domain support

**Comment by aopell** [comment]
Thank you very much for your PR @ChickenBone.

We really want to add support for all domains (as @glen3b mentioned we have an issue for this already - #82), but unfortunately it's not as simple as just adding more to the manifest. The biggest reason for this is any time a new domain is added to the manifest, it changes the permissions requested by the extension meaning it gets disabled for *all existing users*. We can't really afford to do that, as a good number of those people will likely not re-enable the extension.

Our current plan is for, sometime in the (hopefully near) future, to have some kind of new user flow that allows people to pick their domain when you first install Schoology Plus. It's on the roadmap, definitely in our top 5 priorities.

I'm going to leave this PR open for now, and I'll let you know of any updates.

Thanks for your interest in Schoology Plus!

**Comment by glen3b** [comment]
The permissions that we would in practice declare would be [optional permissions](https://developer.chrome.com/docs/extensions/reference/permissions/), and we would have to dynamically set up content script injection. Depending on your coding savvy, if you want to work with us to take a look at this we'd be more than happy to help get you started.

**Comment by aopell** [comment]
This is no longer relevant as of #82

**Pull request closed without merging**
